source 'https://rubygems.org'
gem 'rails', '~> 6.1'
gem 'mysql2'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope'
gem 'florrick'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins'
gem 'http_accept_language'
gem 'net-smtp'
gem 'tzinfo-data'
gem 'rake'

group :development, :test do
  gem 'annotate'
end